defaults:
  - dataset: valentini
  - model: demucs
  - loss: L1_Multi_STFT
  - optimizer: sgd

training:
  num_epochs: 10
  model_save_path: /media/public/checkpoints

dataloader:
  max_seconds: 2
  sample_rate: 16000
  train_batch_size: 12
  valid_batch_size: 12
  normalize: False
  num_workers: 12

validation:
  path: /media/public/datasets/denoising/DS_10283_2791/minimal
  sample_rate: 48000


wandb:
  entity: borisovmaksim
  run_name: default
  project: denoising
  log_interval: 100
  api_key: local-e23d01ece807cb31e69b2cf4137e4998e4b9856f
  host: http://localhost:8080/
  notes: "Experiment note"
  resume: False
  resume_path: None

gpu: 1
